name: Trivy Scan - Docker HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-docker:
    name: Scan Docker Image - HTML Report
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: |
          docker build -t meu-projeto:latest .
      
      - name: Scan da imagem Docker (HTML)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'meu-projeto:latest'
          format: 'html'
          output: 'trivy-docker-report.html'
      
      - name: Upload do relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: trivy-docker-html-report
          path: trivy-docker-report.html
